### PR TITLE
Added support for HD610, UHD620 and P630 (with fake device id)

### PR DESCRIPTION
**Pull request by syscl**
The support set for P630 is incomplete, we need to fake P630’s device-id (0x591D) as HD630(0x591B).

### CODE REVIEW

**Comment by lvs1974** [comment]
Hi syscl,
could you explain where you get those new device ids: 0x5902 & 0x5917?
It seems they are not used in any Info.plist files.

**Comment by syscl** [comment]
@lvs1974  P630's [device id](https://ark.intel.com/products/97478/Intel-Xeon-Processor-E3-1275-v6-8M-Cache-3_80-GHz). HD610, UHD620 and P630 can be found [here](https://pci-ids.ucw.cz/read/PC/8086) as well.

**Comment by vit9696** [comment]
In this case add a fake identitifer for these `device-ids` with an appropriate GPU, since they won't work otherwise.

**Comment by syscl** [comment]
Hi vit, the mechanism to power up P630 is to fake it’s its device id as HD630, same as P530, P4600...

**Comment by vit9696** [comment]
I am aware of that, yet you added 2 more device-ids (HD610, UHD620), which are not natively supported, and thus also need to be faked. Mixing them with natively supported device-ids (present in Info.plist) is misleading, so I request you to fix them (by adding a corresponding fake device-id) too.

**Comment by syscl** [comment]
Sure.

**Comment by vit9696** [comment]
Is it too hard for you to open `/System/Library/Extensions/AppleIntelSKLGraphics.kext/Contents/Info.plist` and check yourself rather than wasting our time discussing 3 issues in a 3-line pull request?

**Comment by syscl** [comment]
@vit9696 The notification on my phone was delayed so that I've received you reply 15 minutes late :(.

**Pull request closed without merging**
